### ISSUE TITLE
The button retry is far too expensive.

### ISSUE THREAD

**Issue by vallettea** [anthill/6bin#42]
Yesterday we had a bug on 6element and bin couldn't be retrieved. So we changed stuf and pressed many times on the retry button. But this button can be pressed so easily that it costed us 9.5euros:

<img width="977" alt="screen shot 2016-01-06 at 09 14 13" src="https://cloud.githubusercontent.com/assets/371303/12138114/890b13e8-b456-11e5-967e-234cb033a5d6.png">

I think we should at least impose a limit to number of times it can be pressed per minutes.

**Comment by vallettea** [comment]
@iOiurson maybe we could ship that as part of the next update.

**Comment by bleucitron** [comment]
I'm surprised.

Of course, we can (and probably must) cap the number of times this button can be pressed, maybe 5 times every 10 minutes or so.

But
- **wasn't this sensor supposed to be connected by cable ?** If so, it shouldn't cost us anything.
- **how could we have consumed 9 Mb by pressing this button ?** It's a simple HTTP request (okay, wrapped within MQTT messages) that most of the times returned empty bin list... and I don't remember pressing it 50 times

Are you absolutely certain this is only due to the sole Retry Button ?

**Comment by vallettea** [comment]
You are right pressing the button cannot be the only cause but maybe it's something around qos 1: N of queries are made and when it finally works pheromons sends N times the result (the big json of the bins)

**Comment by bleucitron** [comment]
We need to investigate this further.
From what i remember, we had plenty of error responses from 6element server (due to the http/https automatic switch thing). This means there was no bin list sent whatsoever: the sensor queried, and had a response. I don't see why bin lists would have been sent later on.

What is true though, is that the `timeout` set on the Retry button (about 5 secondes if i'm correct) can cause such behavior (the bin list received for nothing after the timeout has passed). But i don't believe we're in this case.

Is it possible to have a detailed version of the consumption ? Can we trust the timestamp on the image you shared ?

**Comment by vallettea** [comment]
no we can't have more details, the timestamps are good

**Comment by bleucitron** [comment]
Ok, so this is not due to the http/https problem we had yesterday around 7pm.
This was indeed because of requests from pheromon to 6element that didn't have an answer at first (6element was down).

To fix this, 2 options:
- cap the use of the Retry Button
- fine tune the behavior of pheromon regarding requests from sensors to 6element

The former is probably easier to implement, but might not be generic enough.
